### ISSUE TITLE
[Question] Integrate your code in my Log Viewer?

### ISSUE THREAD

**Issue by LiorBanai** [mo-esmp/serilog-ui#23]
Hi,
I have Log viewer (https://github.com/Analogy-LogViewer) for common log frameworks.

Can I use part of your work/code to create now data sources in my application?

**Comment by mo-esmp** [comment]
Hi @LiorBanai,

Sure, it's an open-source project and you're welcome to use codes.

**Comment by LiorBanai** [comment]
@mo-esmp  Thanks :)
